project:
  type: website
  resources:
    - images

website:
  title: Project Title
  navbar:
    right:
      - icon: github
        href: https://github.com/N-Herling-Mk1/project-final # Needs to be changed to your project repo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    favicon: images/water_drop.ico
    theme:
      light: flatly
      dark: darkly
    toc: true


execute:
  freeze: auto

